---
- name: Create and Apply Network Policy to Block All Traffic in and out of a Pod
  hosts: all
  connection: ssh
  
  tasks:
    - name: Login to OpenShift cluster
      ansible.builtin.command: oc login --token={{ K8S_AUTH_API_KEY }} --server={{ K8S_AUTH_HOST }}

    - name: Change file ownership, group and permissions
      ansible.builtin.file:
        path: network-policy.yaml
        state: touch
      
    - name: Create Network Policy Definition
      ansible.builtin.blockinfile:
        path: network-policy.yaml
        block: |
          apiVersion: networking.k8s.io/v1
          kind: NetworkPolicy
          metadata:
            name: block-all-traffic-policy
            namespace: devops
          spec:
            podSelector: s
              matchLabels:
                app: log4shell-app
            policyTypes:
              - Ingress
              - Egress
          status: {}

    - name: Apply Network Policy
      ansible.builtin.shell: oc apply -f network-policy.yaml
      args:
        executable: /bin/bash

    - name: Notify Slack channel
      community.general.slack:
        token: "T0508SWKB2N/B04V8C4P6A3/fr3b7rtyxJrZgjuRqQ1UCT1d"
        channel: "#devops"
        msg: "*OpenShift Network Policy applied to mitigate risk. Both Ingress and Egress traffic have been disabled. Log4Shell POD is now isloated*"