---
- name: Notify Slack channel
  hosts: all

  tasks:
  
    - name: Post message to Slack channel
      community.general.slack:
        token: "T0508SWKB2N/B04V8C4P6A3/fr3b7rtyxJrZgjuRqQ1UCT1d"
        channel: "#devops"
        msg: "{{ message }}"

    - name: Post URL to Slack channel
      community.general.slack:
        token: "T0508SWKB2N/B04V8C4P6A3/fr3b7rtyxJrZgjuRqQ1UCT1d"
        channel: "#devops"
        msg: "A JNDI injection attack has been identified in Dynatrace. This incident has triggered the following automation workflow in Ansible Automation Platform: https://aap-controller-aap.apps.cluster-6fk65.6fk65.sandbox667.opentlc.com/#/jobs/workflow/{{ awx_workflow_job_id }}/output"