---
- name: Predeployment setup in Azure
  hosts: localhost
  gather_facts: False
  vars_files:
    - 'vars/azure.yml'
  vars:
    teardown: false
  tasks:
  
    - name: Set resource facts
      set_fact:
        azure_resource_group:  "{{ name_prefix }}-resource"
        azure_storage_account: "{{ (name_prefix + 'storage') | lower | regex_replace('[^0-9a-z]+', '') }}"
        azure_virtual_network: "{{ name_prefix }}-network"
        azure_virtual_subnet:  "{{ (name_prefix + 'subnet')  | lower | regex_replace('[^0-9a-z]+', '') }}"
    
    - name: Install specified python requirements for Azure Collection
      ansible.builtin.pip:
        requirements: /usr/share/ansible/collections/ansible_collections/azure/azcollection/requirements-azure.txt

    # Create a resource group
    - name: Azure | Create a resource group
      azure.azcollection.azure_rm_resourcegroup:
        name: "{{ azure_resource_group }}"
        location: "{{ azure_location }}"
        state: present

    # Create a virtual network
    - name: Azure | Create virtual network
      azure.azcollection.azure_rm_virtualnetwork:
        resource_group: "{{ azure_resource_group }}"  
        name: "{{ azure_virtual_network }}"
        address_prefixes_cidr:
            - "{{ ptr_zone_cidr }}"
        dns_servers:
            - "8.8.8.8"
      register: virtual_network_facts    

    # Create a subnet and associate with the virtual network
    - name: Create a subnet
      azure.azcollection.azure_rm_subnet:
        resource_group: "{{ azure_resource_group }}"
        name: "{{ azure_virtual_subnet }}"
        virtual_network_name: "{{ azure_virtual_network }}"
        address_prefix_cidr: "{{ ptr_zone_cidr }}"