---
- name: User lookup using objectId
  azure.azcollection.azure_rm_aduser_info:
    object_id: "{{ object_id }}"
    tenant: 1ce7852f-dcf3-42bc-afe6-3bf81ab984fb
  register: user_data

- name: Print Update Output to Screen
  debug:
    msg: "{{ user_data }}"