---
- name: Using user_principal_name
  azure.azcollection.azure_rm_aduser_info:
    object_id: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
  register: user_data

# - name: Print Update Output to Screen
#   debug:
#     msg: 