---
- name: Disable firewall for Domain, Public, and Private profiles
  community.windows.win_firewall:
    state: disabled
    profiles:
    - Domain
    - Private
    - Public

- name: Install AD-Domain-Services
  ansible.windows.win_feature:
    name: AD-Domain-Services
    state: present
    include_management_tools: True
    include_sub_features: True
  register: winfeature

- name: Reboot if needed
  ansible.windows.win_reboot:
  when: winfeature.changed

- name: Create DNS Domain
  ansible.windows.win_domain:
    dns_domain_name: "{{ dns_domain_name }}"
    safe_mode_password: "{{ ansible_password }}"
  register: windomain

- name: Reboot if needed
  ansible.windows.win_reboot:
  when:
    - windomain.reboot_required

- name: Wait for Active Directory Web Services port
  ansible.windows.win_wait_for:
    host: localhost
    port: 9389
    timeout: 600

- name: Ensure AD Services are started
  ansible.windows.win_service:
    name: "{{ item }}"
    state: started
    start_mode: auto
  with_items:
    - dns
    - adws

# - name: Set Reverse Lookup Zone
#   win_ad_reverse_dnszone:
#     subnet: "{{ ptr_zone_cidr }}"
#     zonename: "{{ ptr_zone_name }}"
#     state: present
#   register: reverse
#   until: reverse is not failed
#   retries: 100

- name: Add windows group
  community.windows.win_domain_group:
    name: Ansible Users
    scope: global

- name: Add windows domain admin
  community.windows.win_domain_user:
    name: "Admin"
    upn: "Admin@{{ dns_domain_name }}"
    state: present
    enabled: yes
    account_locked: no
    groups:
      - Domain Admins
    password: "{{ domain_admin_password }}"
    update_password: on_create
    password_expired: false
    firstname: admin
    surname: user
    company: AnsibleByRedHat
    email: "Admin@{{ dns_domain_name }}"

- name: Add windows AD users
  community.windows.win_domain_user:
    name: "{{ user_prefix }}{{ item }}"
    upn: "{{ user_prefix }}{{ item }}@{{ dns_domain_name }}"
    state: present
    enabled: yes
    account_locked: no
    groups:
      - Ansible Users
    password: "{{ users_password }}"
    update_password: on_create
    password_expired: false
    firstname: "{{ user_prefix }}"
    surname: "{{ item }}"
    company: AnsibleByRedHat
    email: "{{ user_prefix }}{{ item }}@{{ dns_domain_name }}"
  with_sequence: count="{{ user_count }}"

# - name: Set DNS search string to {{ dns_domain_name }}
#   win_dns_searchsuffix:
#     suffixes:
#       - "{{ dns_domain_name }}"