---
- name: Check for Windows updates on instances in Azure
  hosts: all
  connection: local
  become: false
  gather_facts: false
  tasks:

    - name: Include default variables for patching
      ansible.builtin.include_vars: ../../vars/azure.yml

    ## Instance creation
    - ansible.builtin.include_role:
        name: ../../roles/azure_update_check_windows
