---
- name: Update Windows instances in Azure
  hosts: all
  connection: local
  become: false
  gather_facts: true
  tasks:

    - name: Include default variables for provisioning
      ansible.builtin.include_vars: ../../vars/azure.yml

    ## Instance creation
    - name: Create instance
      ansible.builtin.include_role:
        name: ../../roles/azure_win_2022_cis