---
- name: Create resources and instances in Azure
  hosts: localhost
  connection: local
  become: false
  gather_facts: false
  tasks:
  
    - name: Include default variables for provisioning
      ansible.builtin.include_vars: ../../vars/azure.yml

    - name: Windows | Wait for {{ windows_ansible_connection | default('winrm') }} to come up
      ansible.builtin.wait_for_connection:
      delegate_to: "{{ item }}"
      with_items: "{{ groups['windows'] }}" 