---
- name: ServiceNow Create Change Request
  hosts: localhost
  connection: local
  gather_facts: no

  tasks:

    - name: Wait for Change Request approval
      servicenow.itsm.change_request_info:
        instance:
          host: "{{ snow_instance }}"
          username: "{{ snow_username }}"
          password: "{{ snow_password }}"
        number: "{{ chg_number }}"
      until: change_request_status.records[0].state == "implement"
      retries: 300
      delay: 10
      register: change_request_status

    - name: Update the change request to review in ServiceNow
      servicenow.itsm.change_request:
        instance:
          host: "{{ snow_instance }}"
          username: "{{ snow_username }}"
          password: "{{ snow_password }}"
        state: review
        number: "{{ chg_number }}"
