---
- name: ServiceNow Close Incident
  hosts: localhost
  connection: local
  gather_facts: no
  
  tasks:

    # - name: Close Incident
    #   snow_record :
    #     username: "{{ snow_username }}"
    #     password: "{{ snow_password }}"
    #     instance: "{{ snow_instance }}"
    #     state: present
    #     number: "{{ inc_number }}"
    #     data:
    #       state: 6
    #       close_code: "Resolved by change"
    #       close_notes: "{{ close_notes }}"
    #       work_notes: "This incident has been closed by Ansible"
    #   register: new_incident

    - name: Close change request
      servicenow.itsm.incident:
        instance:
          host: "{{ snow_instance }}"
          username: "{{ snow_username }}"
          password: "{{ snow_password }}"

        state: closed
        # requested_by: some.user
        close_code: "Resolved by change"
        close_notes: "{{ close_notes }}"
        # assignment_group: "Software"
        number: "{{ inc_number }}"
        other:
          work_notes: "This incident has been closed by Ansible Automation Platform"