---
- name: ServiceNow Create Incident
  hosts: localhost
  connection: local
  gather_facts: no
  
  tasks:

    - name: Create Incident
      snow_record:
        username: "{{ snow_username }}"
        password: "{{ snow_password }}"
        instance: "{{ snow_instance }}"
        state: present
        data:
          short_description: "{{ short_description }}"
          urgency: "{{ urgency }}"
          impact: "{{ impact }}"
          assigned_to: "{{ assigned_to }}"
          caller_id: "{{ caller_id }}"
      register: new_incident