---
- name: ServiceNow Notification
  hosts: localhost
  connection: local
  gather_facts: no
  
  tasks:

    - name: Update ServiceNow ticket to indicate start
      servicenow.itsm.api:
        instance:
          host: "{{ snow_instance }}"
          username: "{{ snow_username }}"
          password: "{{ snow_password }}"

        resource: sc_request
        action: patch
        sys_id: "{{ sys_id }}"
        data:
          work_notes: "{{ snow_note }}"
      register: snow_var