---
- name: ServiceNow Create Change Request
  hosts: localhost
  connection: local
  gather_facts: no

  tasks:

    - name: Create change request
      servicenow.itsm.change_request:
        instance:
          host: "{{ snow_instance }}"
          username: "{{ snow_username }}"
          password: "{{ snow_password }}"

        type: "{{ chg_type }}"
        state: authorize
        # requested_by: some.user
        short_description: "{{ short_description }}"
        description: "{{ description }}"
        priority: "{{ priority }}"
        risk: "{{ risk }}"
        impact: "{{ impact }}"
        assignment_group: "CAB Approval"

        other:
          assigned_to: "{{ assigned_to }}"
      register: new_chg_request

    - name: Set resource facts
      ansible.builtin.set_fact:
        chg_number: "{{ new_chg_request.record.number }}"
    
    - name: set stats
      ansible.builtin.set_stats:
        data:
          chg_number: "{{ new_chg_request.record.number }}"

    - name: Print Message
      ansible.builtin.debug:
        var: new_chg_request.record.number

    - name: Post URL to Slack channel
      community.general.slack:
        token: "T0508SWKB2N/B04V8C4P6A3/fr3b7rtyxJrZgjuRqQ1UCT1d"
        channel: "#devops"
        msg: "{{ assigned_to }} has a new change request approval to action. Please click on this URL to approve: {{ snow_instance }}/nav_to.do?uri=change_request.do?sysparm_query=number={{ chg_number }}"

    - name: Wait for Change Request approval
      servicenow.itsm.change_request_info:
        instance:
          host: "{{ snow_instance }}"
          username: "{{ snow_username }}"
          password: "{{ snow_password }}"
        number: "{{ chg_number }}"
      until: change_request_status.records[0].state == "implement"
      retries: 100
      delay: 10
      register: change_request_status

    - name: Update the change request to review in ServiceNow
      servicenow.itsm.change_request:
        instance:
          host: "{{ snow_instance }}"
          username: "{{ snow_username }}"
          password: "{{ snow_password }}"
        state: review
        number: "{{ chg_number }}"
