---
- name: ServiceNow Create Change Request
  hosts: localhost
  connection: local
  gather_facts: no

  tasks:

    - name: Create change request
      servicenow.itsm.change_request:
        instance:
          host: "{{ snow_instance }}"
          username: "{{ snow_username }}"
          password: "{{ snow_password }}"

        type: "{{ chg_type }}"
        state: new
        # requested_by: some.user
        short_description: "{{ short_description }}"
        description: "{{ description }}"
        priority: "{{ priority }}"
        risk: "{{ risk }}"
        impact: "{{ impact }}"
        assignment_group: "CAB Approval"

        other:
          assigned_to: "{{ assigned_to }}"
      register: new_chg_request

    - name: set stats
      set_stats:
        data:
          chg_number: "{{ new_chg_request.record.number }}"

    - name: Print Message
      debug:
        var: new_chg_request.record.number

    - name: Wait for Change Request approval
      servicenow.itsm.change_request_info:
        number: "{{ chg_number }}"
      until: change_request_status.records[0].state == "scheduled"
      retries: 100
      delay: 10
