---
- name: ServiceNow Gather Catalog Request Info
  hosts: localhost
  connection: local
  gather_facts: no
  
  tasks:

    - name: Retrieve all records from catalog requests
      servicenow.itsm.api_info:
        instance:
          host: "{{ snow_instance }}"
          username: "{{ snow_username }}"
          password: "{{ snow_password }}"
        resource: sc_request
      register: catalog_requests

    - name: Print most recent record
      debug:
        msg: "First item: {{ record[0] }}"