---
- name: ServiceNow Notification
  hosts: localhost
  connection: local
  gather_facts: no
  
  tasks:

    # - name: Update ServiceNow ticket to indicate start
    #   snow_record:
    #     username: "{{ snow_username }}"
    #     password: "{{ snow_password }}"
    #     instance: "{{ snow_instance }}"
    #     state: present
    #     table: sc_request
    #     number: "{{ snow_request }}"
    #     data: 
    #       work_notes: "{{ snow_note }}"
    #   register: snow_var

    - name: Update ServiceNow ticket to indicate start
      servicenow.itsm.api:
        instance:
          host: "{{ snow_instance }}"
          username: "{{ snow_username }}"
          password: "{{ snow_password }}"

        resource: sc_request
        action: patch
        other:
          work_notes: "{{ snow_note }}"
          number: "{{ snow_request }}"
      register: snow_var