---
- name: ServiceNow Create Change Request
  hosts: localhost
  connection: local
  gather_facts: no

  tasks:

    - name: Create change request
      servicenow.itsm.change_request:
        instance:
          host: "{{ snow_host }}"
          username: "{{ snow_username }}"
          password: "{{ snow_password }}"

        type: standard
        state: new
        # requested_by: some.user
        short_description: Install new Cisco
        description: Please install new Cat. 6500 in Data center 01
        priority: moderate
        risk: high
        impact: medium
      register: new_chg_request

    - name: set stats
      set_stats:
        data:
          chg_number: "{{ new_chg_request.record.number }}"

    - name: Print Message
      debug:
        var: new_chg_request.record.number
