---
- name: ServiceNow Create Change Request
  hosts: localhost
  connection: local
  gather_facts: no

  tasks:

    - name: Close change request
      servicenow.itsm.change_request:
        instance:
          host: "{{ snow_host }}"
          username: "{{ snow_username }}"
          password: "{{ snow_password }}"

        state: closed
        # requested_by: some.user
        close_code: "successful"
        close_notes: "{{ close_notes }}"
        assignment_group: "Software"
        number: "{{ chg_number }}"