---
- name: ServiceNow Create Incident
  hosts: localhost
  connection: local
  gather_facts: no
  
  tasks:

    - name: Create Incident
      servicenow.itsm.incident:
        instance:
          host: "{{ snow_instance }}"
          username: "{{ snow_username }}"
          password: "{{ snow_password }}"

        state: new
        short_description: "{{ short_description }}"
        urgency: "{{ urgency }}"
        impact: "{{ impact }}"
        description: "{{ description }}"
        other:
          assigned_to: "{{ assigned_to }}"
          caller_id: "{{ caller_id }}"
      register: new_incident

    - name: set stats
      set_stats:
        data:
          inc_number: "{{ new_incident.record.number }}"

    - name: Print Message
      debug:
        var: new_incident.record.number