---
- name: Windows Update Check
  ansible.windows.win_updates:
    state: searched
    category_names: '*'
  register: available_updates

- name: Print Update Output to Screen
  debug:
    msg: |
      {{ inventory_hostname }} has {{ available_updates.found_update_count }} updates available.
      {% for key, value in available_updates.updates.items() %}
      - KB: {{ value.title }}
      {% endfor %}

- name: Update ServiceNow ticket to indicate start
  servicenow.itsm.api:
    instance:
      host: "{{ snow_instance }}"
      username: "{{ snow_username }}"
      password: "{{ snow_password }}"

    resource: sc_request
    action: patch
    sys_id: "{{ sys_id }}"
    data:
      work_notes:  |
        {{ inventory_hostname }} has {{ available_updates.found_update_count }} updates available.
        {% for key, value in available_updates.updates.items() %}
        - KB: {{ value.title }}
        {% endfor %}