---
- name: Windows Update Check
  ansible.windows.win_updates:
    state: searched
    category_names: '*'
  register: available_updates

- name: Print Update Output to Screen
  debug:
    msg: |
      {{ inventory_hostname }} has {{ available_updates.found_update_count }} updates available.
      {% for key, value in available_updates.updates.items() %}
      - KB: {{ value.title }}
      {% endfor %}

- name: Update ServiceNow Ticket Work Notes 
  ansible.builtin.set_stats:
    data:
      description: "{{ inventory_hostname }} has {{ available_updates.found_update_count }} updates available.
        {% for key, value in available_updates.updates.items() %}
        - KB: {{ value.title }}
        {% endfor %}"