---
- name: Windows Update Check
  ansible.windows.win_updates:
    state: searched
    category_names: '*'
  register: win_update_result

- name: Print Message
  debug:
    msg: "{{ win_update_result.update.title }}"

- name: Print Message
  debug:
    var: win_update_result.update.title

- name: Set client secret and ID variables
  set_fact:
    win_updates: "{{ win_update_result.update.title }}"

- name: Update ServiceNow ticket to indicate start
  servicenow.itsm.api:
    instance:
      host: "{{ snow_instance }}"
      username: "{{ snow_username }}"
      password: "{{ snow_password }}"

    resource: sc_request
    action: patch
    sys_id: "{{ sys_id }}"
    data:
      work_notes: "The current required updates on {{ ansible_host }} are: 
        
        {{ win_updates }}"
  register: snow_var