---
- name: Bounce port
  hosts: all
  gather_facts: false
  tasks:

    # - name: For idempotency, use full-form commands
    #   cisco.ios.ios_config:
    #     lines:
    #       - shutdown
    #     parents: interface GigabitEthernet1/0/11

    # - name: Sleep for 20 seconds and continue
    #   ansible.builtin.wait_for:
    #     timeout: 20
    #   delegate_to: localhost

    - name: Bounce port
      cisco.ios.ios_config:
        lines:
          - no shutdown
        parents: interface GigabitEthernet1
