---
- name: Create resources in AWS
  hosts: localhost
  connection: local
  become: false
  gather_facts: false
  tasks:
  
    - name: Include default variables for provisioning
      ansible.builtin.include_vars: ../../vars/aws_rhel.yml

    - name: Include default vpc rules for provisioning
      ansible.builtin.include_vars: ../../vars/vpc_rules.yml
    
    - name: ensure workshop folder {{ ec2_name_prefix }} exists
      ansible.builtin.file:
        path: "{{ playbook_dir }}/{{ ec2_name_prefix }}"
        state: directory
    
    ## build network elements, security groups and key pair
    - ansible.builtin.include_role:
        name: ../../roles/aws_resources

    ## find AMI dynamically
    - ansible.builtin.include_role:
        name: ../../roles/ami_find/{{ workshop_type }}_ami

    ## Instance creation
    - ansible.builtin.include_role:
        name: ../../roles/aws_instances/{{ workshop_type }}