---
- name: Create resources and instances in AWS
  hosts: localhost
  connection: local
  become: false
  gather_facts: false
  vars:
    workshop_type: network

  tasks:

    - name: Include default variables for provisioning
      ansible.builtin.include_vars: ../../vars/aws.yml

    - name: Include default vpc rules for provisioning
      ansible.builtin.include_vars: ../../vars/vpc_rules.yml

    - name: Ensure workshop folder {{ ec2_name_prefix }} exists
      ansible.builtin.file:
        path: "{{ playbook_dir }}/{{ ec2_name_prefix }}"
        state: directory

    ## build network elements, security groups and key pair
    - name: Build network elements, security groups and key pair
      ansible.builtin.include_role:
        name: ../../roles/aws_resources

    ## Duplicates the above for network using 2 VPCs
    - name: Duplicates the above for network using 2 VPCs
      ansible.builtin.include_role:
        name: ../../roles/aws_resources_network

    ## find AMI dynamically
    - name: Find AMI dynamically
      ansible.builtin.include_role:
        name: ../../roles/ami_find_{{ workshop_type }}

    ## Instance creation
    - name: Network instance creation
      ansible.builtin.include_role:
        name: ../../roles/aws_instances_{{ workshop_type }}

    ## Configure network device setup
    # - name: Include workshop_type unique setup roles
    #   ansible.builtin.import_playbook: "{{ playbook_dir }}/workshop_specific/{{ workshop_type }}.yml"
