---
- name: Create resources in AWS
  hosts: localhost
  connection: local
  become: false
  gather_facts: false
  tasks:
  
    - name: Include default variables for provisioning
      ansible.builtin.include_vars: ../../vars/main.yml

    - name: Include default vpc rules for provisioning
      ansible.builtin.include_vars: ../../vars/vpc_rules.yml
    
    - name: ensure workshop folder {{ ec2_name_prefix }} exists
      ansible.builtin.file:
        path: "{{ playbook_dir }}/{{ ec2_name_prefix }}"
        state: directory
    
    ## build network elements, security groups and key pair
    - ansible.builtin.include_role:
        name: ../../roles/resources

    ## find AMI dynamically
    - name: find correct AMI
      include_tasks: 'ami_find/ami_find_{{ workshop_type }}.yml'

    ## Instance creation
    - name: provision workshop instances
      include_tasks: 'instances/instances_{{ workshop_type }}.yml'