---
- name: Create resources in AWS
  hosts: localhost
  connection: local
  become: false
  gather_facts: false
  tasks:
  
    - name: Include default variables for provisioning
      ansible.builtin.include_vars: ../../vars/main.yml
    
    - name: ensure workshop folder {{ ec2_name_prefix }} exists
      ansible.builtin.file:
        path: "{{ playbook_dir }}/{{ ec2_name_prefix }}"
        state: directory
    
    - ansible.builtin.include_role:
        name: resources