---
- name:  RHEL Update
  hosts: all
  become: false
  gather_facts: false
  tasks:
  
    - name: Include default variables
      ansible.builtin.include_vars: ../../vars/aws.yml

    ## Instance update
    - ansible.builtin.include_role:
        name: ../../roles/aws_update_rhel