---
- name: System Setup
  hosts: all
  become: true

  tasks:

    - name: Update all security-related packages
      ansible.builtin.dnf:
        name: '*'
        state: latest
        security: true

    - name: Create a new user
      ansible.builtin.user:
        name: myuser
        state: present
        create_home: true
        group: admin

    - name: Give new user sudo privileges (wheel group)
      ansible.builtin.user:
        name: myuser
        groups: wheel
        append: true

    - name: Ensure user is present
      block:
        - name: Check user existence
          ansible.builtin.command:
            cmd: id myuser
          register: user_check

        - name: Report on present user account
          ansible.builtin.debug:
            msg: "User 'myuser' exists."
          when: user_check.rc == 0

        - name: Report on absent user account
          ansible.builtin.debug:
            msg: "User 'myuser' does not exists."
          when: user_check.rc != 0

    - name: Ensure user is present
      ansible.builtin.package:
        name: "{{ item }}"
        state: present
      with_items:
        - NetworkManager
        - chrony
        - sysstat
        - httpd
        - vim
        - bind-utils

    - name: Start Apache service
      ansible.builtin.service:
        name: httpd
        state: started

    - name: Create dhclient.conf file
      ansible.builtin.file:
        path: /etc/dhcp/dhclient.conf
        state: touch
        owner: root
        group: root
        mode: '0644'

    - name: Set custom DNS server for DHCP
      ansible.builtin.blockinfile:
        dest: /etc/dhcp/dhclient.conf
        block: |
          prepend domain-name-servers 8.8.8.8;
        state: present
      register: dnschange

    - name: Restart NetworkManager
      ansible.builtin.service:
        name: NetworkManager
        state: restarted
      when: dnschange.changed

    - name: Add EPEL repo for RHEL 8
      ansible.builtin.yum_repository:
        name: epel
        description: EPEL for Enterprise Linux 8
        baseurl: https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm
        enabled: true
        gpgcheck: false
      when: ansible_distribution_major_version | int == 8

    - name: Add EPEL repo for RHEL 9
      ansible.builtin.yum_repository:
        name: epel
        description: EPEL for Enterprise Linux 9
        baseurl: https://dl.fedoraproject.org/pub/epel/epel-release-latest-9.noarch.rpm
        enabled: true
        gpgcheck: false
      when: ansible_distribution_major_version | int == 9

    - name: Check to see the current status of FIPS mode
      command: /usr/bin/fips-mode-setup --check
      register: is_fips_enabled
      changed_when: false
      failed_when: false

    - name: Enable FIPS mode
      command: /usr/bin/fips-mode-setup --enable

    - name: Ensure openscap-scanner is installed
      package:
        name: openscap-scanner
        state: present