---
- name: Run basic PowerShell script
  ansible.windows.win_powershell:
    script: |
      Invoke-WebRequest -Uri "https://sensor.cloud.tenable.com/install/scanner/installer/ms-install-script.ps1" -OutFile "./ms-install-script.ps1"; & "./ms-install-script.ps1" -key "{{ nessus_key }}" -type "scanner" -name "{{ name_prefix + '-s' + item + '-w1'}}" -groups 'rhwindows'; Remove-Item -Path "./ms-install-script.ps1"

- name: Update ServiceNow Ticket Work Notes
  ansible.builtin.set_stats:
    data:
      snow_note: "Tenable Nessus agent successfully installed"
