---
- name: Tenable vulnerabilities export
  hosts: localhost
  gather_facts: no

  tasks:

    - name: Export vulnerabilities
      ansible.builtin.uri:
        url: "https://cloud.tenable.com/vulns/export"
        method: POST
        headers:
          X-ApiKeys: "accessKey={{ access_key }};secretKey={{ secret_key }}"
          accept: application/json
          content-type: application/json
      register: vuln_export

    - name: Print Message
      ansible.builtin.debug:
        msg: "{{ vuln_export }}"

    - name: Print Message
      ansible.builtin.debug:
        var: vuln_export.json.export_uuid

    - name: Set export UUID
      ansible.builtin.set_fact:
        export_uuid: "{{ vuln_export.json.export_uuid }}"

    - name: Print Message
      ansible.builtin.debug:
        msg:
          - "This is your export UUID: {{ export_uuid }}"

    - name: Sleep for 10 seconds and continue
      ansible.builtin.wait_for:
        timeout: 10

    - name: Export vulnerabilities status
      ansible.builtin.uri:
        url: "https://cloud.tenable.com/vulns/export/{{ export_uuid }}/status"
        method: GET
        headers:
          X-ApiKeys: "accessKey={{ access_key }};secretKey={{ secret_key }}"
          accept: application/json
      register: vuln_status

    - name: Print Message
      ansible.builtin.debug:
        msg: "{{ vuln_status }}"

    - name: Print Message
      ansible.builtin.debug:
        var: vuln_status.json.chunks_available

    - name: Set chunks available
      ansible.builtin.set_fact:
        chunk_id: "{{ vuln_status.json.chunks_available }}"

    - name: Download vulnerabilities chunk
      ansible.builtin.uri:
        url: "https://cloud.tenable.com/vulns/export/{{ export_uuid }}/chunks/1"
        method: GET
        headers:
          X-ApiKeys: "accessKey={{ access_key }};secretKey={{ secret_key }}"
          accept: application/octet-stream
      register: vuln_chunk

    - name: Print Message
      ansible.builtin.debug:
        msg: "{{ vuln_chunk }}"
