---
- name: Tenable vulnerabilities export
  hosts: localhost
  gather_facts: no

  tasks:

    - name: Export vulnerabilities
      ansible.builtin.uri:
        url: "https://cloud.tenable.com/vulns/export"
        method: POST
        headers:
          X-ApiKeys: accessKey=fa095c9ed880dbc2ce2ec7fb28057ca80c4fe559868d8fd0cfd21777fae64015;secretKey=172e2fa3b3fe8a6efcb325ea415ef0904901b42d08eb0344dbfebfc0e92ca28e
          accept: application/json
          content-type: application/json
      register: vuln_export

    - name: Print Message
      ansible.builtin.debug:
        msg: "{{ vuln_export }}"

    - name: Print Message
      ansible.builtin.debug:
        var: vuln_export.json.export_uuid

    - name: Set export UUID
      ansible.builtin.set_fact:
        export_uuid: "{{ vuln_export.json.export_uuid }}"

    - name: Print Message
      ansible.builtin.debug:
        msg:
        - "This is your export UUID: {{ export_uuid }}"

    # - name: Export vulnerabilities
    #   ansible.builtin.uri:
    #     url: "https://cloud.tenable.com/vulns/export"
    #     method: POST
    #     headers:
    #       X-ApiKeys: accessKey=fa095c9ed880dbc2ce2ec7fb28057ca80c4fe559868d8fd0cfd21777fae64015;secretKey=172e2fa3b3fe8a6efcb325ea415ef0904901b42d08eb0344dbfebfc0e92ca28e
    #       accept: application/json
    #       content-type: application/json
    #   register: vuln_export
