---
- name: Resolve CVE on Windows Hosts
  hosts: all
  connection: local
  become: false
  gather_facts: false
  tasks:

    - name: Include default variables for Azure
      ansible.builtin.include_vars: ../../vars/azure.yml

    ## Instance creation
    - name: Resolve vulnerability with Registry update
      ansible.windows.win_regedit:
        path: HKLM:\Software\Microsoft\Cryptography\Wintrust\Config\EnableCertPaddingCheck
        data: 1
        state: present
