---
- name: Install Nessus Agent on Windows Hosts
  hosts: all
  connection: local
  become: false
  gather_facts: false
  tasks:

    - name: Include default variables for Azure
      ansible.builtin.include_vars: ../../vars/azure.yml

    ## Nessus agent install
    - name: Include Nessus agent install role
      ansible.builtin.include_role:
        name: ../../roles/azure_nessus_install_windows
