---
- name: CONFIGURE CISCO DEVICE
  hosts: all
  connection: network_cli
  gather_facts: false

  vars:
    ntp_server: "216.239.35.0"

  tasks:

    - name: Apply provided hostname configuration
      cisco.ios.ios_hostname:
        config:
          hostname: "{{ cpe_hostname }}"
        state: merged

    - name: Apply provided management IP and subnet configuration
      cisco.ios.ios_config:
        lines:
          - "ip address {{ mgmt_ip }} {{ subnet }}"
          - ip default-gateway "{{ default_gateway }}"

    # - name: FETCH NTP STATUS
    #   ios_command:
    #     commands:
    #       - show ntp config
    #       - show ntp status
    #   register: ntp_config

    # - name: DISPLAY NTP STATUS INTO TERMINAL WINDOW
    #   debug:
    #     msg: "{{ntp_config.stdout_lines}}"