---
- name: CONFIGURE CISCO DEVICE
  hosts: all
  connection: network_cli
  gather_facts: false

  vars:
    ntp_server: "216.239.35.0"

  tasks:

    - name: Apply provided hostname configuration
      cisco.ios.ios_hostname:
        config:
          hostname: "{{ cpe_hostname }}"
        state: merged

    - name: Apply provided management IP and subnet configuration
      cisco.ios.ios_config:
        lines:
          - "ip address {{ mgmt_ip }} {{ subnet }}"
        parents: interface Loopback 0

    - name: Apply provided default gateway configuration
      cisco.ios.ios_config:
        lines:
          - "ip default-gateway {{ default_gateway }}"
