---
- hosts: localhost
  gather_facts: no

  tasks:

    - name: Grab Workflow Template
      ansible.builtin.uri:
        url: "https://{{ controller_url_prefix }}.{{ controller_url_suffix }}/api/v2/workflow_job_templates/"
        user: "{{ uri_user }}"
        password: "{{ uri_password }}"
        method: GET
        force_basic_auth: true
        validate_certs: false
      register: wt_result

    - name: Print Message
      debug:
        msg: "{{ wt_result }}"

    - name: Print Message
      debug:
        var: wt_result.json.results.[id]
      # register: client_secret

    - name: Set client secret and ID variables
      set_fact:
        workflow_id: "{{ wt_result.json.results.[id] }}"

    - name: Print Message
      debug:
        msg: 
        - "This is your Workflow ID: {{ workflow_id }}"
