---
- hosts: localhost
  gather_facts: no
  vars:
    controller_validate_certs: false
    # Controller user for URI module call
    uri_user: admin
    # Controller user password for URI module call
    uri_password: MTM4ODkx
    # Controller base URL prefix (e.g. aap-controller.4rr4p)
    controller_url_prefix: aap-controller.xn54k
    # Controller base URL suffix (e.g. sandbox2307.opentlc.com)
    controller_url_suffix: sandbox2343.opentlc.com

  tasks:

    - name: Set AAP certificate
      set_fact:
        pem_aap_certificate: "{{ lookup('file', '/etc/tower/tower.cert') }}"
