---
- name: ServiceNow Close Incident
  hosts: localhost
  connection: local
  gather_facts: no
  
  tasks:

    - name: Close Incident
      snow_record:
        username: "{{ snow_username }}"
        password: "{{ snow_password }}"
        instance: "{{ snow_instance }}"
        state: present
        number: "{{ inc_number }}"
        data:
          state: 6
          close_code: "Resolved by caller"
          close_notes: "{{ close_notes }}"
          work_notes: "This incident has been closed by Ansible"
      register: new_incident