---
- name: ServiceNow Create Change Request
  hosts: localhost
  connection: local
  gather_facts: no

  tasks:

    - name: Create change request
      servicenow.itsm.change_request:
        instance:
          host: "{{ snow_host }}"
          username: "{{ snow_username }}"
          password: "{{ snow_password }}"

        type: standard
        state: new
        # requested_by: some.user
        short_description: Install new Cisco
        description: Please install new Cat. 6500 in Data center 01
        priority: moderate
        risk: high
        impact: medium



# - name: ServiceNow Create Incident
#   hosts: localhost
#   connection: local
#   gather_facts: no
  
#   tasks:

#     - name: Create Incident
#       snow_record:
#         username: "{{ snow_username }}"
#         password: "{{ snow_password }}"
#         instance: "{{ snow_instance }}"
#         state: present
#         data:
#           short_description: "This is a test incident opened by Ansible"
#           urgency: 1
#           impact: 2
#       register: new_incident